server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.40.128:3306/demo?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    password: root
    username: root

logging:
  config:
  level:
    com.example: debug

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/**Mapper.xml
  global-config:
    db-config:
      id-type: UUID
